# Generated by Django 4.2.16 on 2024-09-09 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Organization Name')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_person_name', models.CharField(max_length=200, verbose_name='Contact Person Name')),
                ('contact_person_mobile', models.CharField(max_length=15, verbose_name='Contact Person Model')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_product_id', models.CharField(max_length=300, verbose_name='Payment ID')),
                ('name', models.CharField(max_length=200, verbose_name='Payment Name')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_set', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price')),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End date')),
                ('is_activate', models.BooleanField(default=True, verbose_name='Is Activate')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('payment_status', models.CharField(choices=[('failed', 'Failed'), ('completed', 'Completed')], max_length=100, verbose_name='Payment Status')),
                ('payment_method', models.CharField(default='card', max_length=100, verbose_name='Payment Method')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_set', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=300, verbose_name='Price ID')),
                ('lookup_key', models.CharField(blank=True, max_length=300, null=True, verbose_name='Lookup Key')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price_set', to='organization.product')),
            ],
        ),
    ]
