# Generated by Django 4.2.16 on 2024-09-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='organization/image/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='organization/product/image/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='reccuring',
            field=models.BooleanField(default=True, verbose_name='Reccuring'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='organization/subscription-invoice/', verbose_name='Invoice'),
        ),
    ]
