# Generated by Django 4.2.16 on 2024-09-09 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_remove_product_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reccuring',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Reccuring'),
        ),
        migrations.AddField(
            model_name='product',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Price ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_set', to='organization.product'),
        ),
        migrations.DeleteModel(
            name='ProductPrice',
        ),
    ]
